# Generated by Django 4.1.4 on 2023-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vacations',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vacations',
            name='is_by_schedule',
            field=models.BooleanField(null=True),
        ),
    ]
